name: SMP
version: 2.5
author: Sshawarma
main: me.Sshawarma.SMP.Main
description: Simple plugin with useful SMP features.
api-version: 1.13
commands:
  find:
    description: asks target for coordinates